{% raw %}
name: Docs CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MicroMamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.6-0' # any version from https://github.com/mamba-org/micromamba-releases
          environment-file: environment.yaml
          init-shell: bash
          cache-environment: true
      - name: Install dependencies
        run: |
          python -m pip install .[docs]
        shell: micromamba-shell {0}
      - name: Build documentation
        run: |
          mkdocs build
        shell: micromamba-shell {0}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
{% endraw %}