site_name: Cookiecutter MLOps
site_description: A project template and directory structure for Python data science projects with MLOps practices.
repo_url: https://github.com/diegocanales/cookiecutter-mlops
edit_uri: edit/master/docs/docs
copyright: Project maintained by Diego Canales.
theme: cinder
extra_css:
  - css/extra.css
nave:
  - Home: index.md
